### ISSUE TITLE
tkinter module not found error

### ISSUE THREAD

**Issue by Yashsethi24** [NikhilAsogekar3/Character-control-using-body-posture#4]
Hi Nikhil! Great work.
I am getting this error.
*************************************
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-2b6d7bd398f7> in <module>
      2 import mediapipe as mp
      3 import numpy as np
----> 4 from tkinter import *
      5 import random
      6 import time

~/.pyenv/versions/3.6.10/lib/python3.6/tkinter/__init__.py in <module>
     34 import sys
     35 
---> 36 import _tkinter # If this fails your Python may not be configured for Tk
     37 TclError = _tkinter.TclError
     38 from tkinter.constants import *

ModuleNotFoundError: No module named '_tkinter'
*****************************************

Any idea how to solve this?

**Comment by NikhilAsogekar3** [comment]
# for pip and windows, in cmd, write:
pip install tk
